// s3-presigned-post-uploads-express-vs-nest/express/client/src/App.jsx
import { useEffect, useRef, useState } from "react";
import { listUploads, uploadFile, downloadUrl, deleteUpload } from "./api.js";

const fmtSize = (b) =>
  b < 1024
    ? `${b} B`
    : b < 1024 * 1024
      ? `${(b / 1024).toFixed(0)} KB`
      : `${(b / 1024 / 1024).toFixed(1)} MB`;

export default function App() {
  const [rows, setRows] = useState([]);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  const fileRef = useRef(null);

  const refresh = async () => setRows(await listUploads());
  useEffect(() => {
    refresh();
  }, []);

  const onUpload = async () => {
    const file = fileRef.current?.files[0];
    if (!file) {
      setStatus("Pick a PDF first.");
      return;
    }
    setBusy(true);
    try {
      await uploadFile(file, setStatus);
      setStatus("Done.");
      fileRef.current.value = "";
      refresh();
    } catch (e) {
      setStatus(e.message);
    } finally {
      setBusy(false);
    }
  };

  const onDownload = async (id) => {
    window.open(await downloadUrl(id), "_blank");
  };

  // Hard delete — confirm first (bytes are gone for good, no soft-delete here).
  const onDelete = async (id, filename) => {
    if (!window.confirm(`Delete "${filename}"? This can't be undone.`)) return;
    setBusy(true);
    try {
      await deleteUpload(id);
      setStatus("Deleted.");
      refresh();
    } catch (e) {
      setStatus(e.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <main>
      <h1>
        File uploads <span className="tag">express + react</span>
      </h1>
      <p className="hint">
        PDF only, up to the server's size cap. The file goes straight to storage
        — it never passes through this server.
      </p>

      <section className="uploader">
        <input type="file" accept="application/pdf" ref={fileRef} />
        <button onClick={onUpload} disabled={busy}>
          Upload
        </button>
        <span className="status">{status}</span>
      </section>

      <h2>Uploads</h2>
      <ul className="list">
        {rows.length === 0 && <li className="empty">No uploads yet.</li>}
        {rows.map((r) => (
          <li key={r.id}>
            <div>
              <div className="name">{r.filename}</div>
              <div className="meta">
                {fmtSize(r.size)} · {new Date(r.createdAt).toLocaleString()}
              </div>
            </div>
            <div className="row-actions">
              <span className={`badge ${r.status}`}>{r.status}</span>
              {r.status === "uploaded" && (
                <button className="link" onClick={() => onDownload(r.id)}>
                  Download
                </button>
              )}
              <button
                className="link danger"
                onClick={() => onDelete(r.id, r.filename)}
                disabled={busy}
              >
                Delete
              </button>
            </div>
          </li>
        ))}
      </ul>
    </main>
  );
}

// s3-presigned-post-uploads-express-vs-nest/nestjs/client/src/App.svelte
<script>
  import { onMount } from "svelte";
  import { listUploads, uploadFile, downloadUrl, deleteUpload } from "./api.js";

  let rows = [];
  let status = "";
  let busy = false;
  let fileInput;

  const fmtSize = (b) =>
    b < 1024
      ? `${b} B`
      : b < 1024 * 1024
        ? `${(b / 1024).toFixed(0)} KB`
        : `${(b / 1024 / 1024).toFixed(1)} MB`;

  async function refresh() {
    rows = await listUploads();
  }
  onMount(refresh);

  async function onUpload() {
    const file = fileInput.files[0];
    if (!file) {
      status = "Pick a PDF first.";
      return;
    }
    busy = true;
    try {
      await uploadFile(file, (s) => (status = s));
      status = "Done.";
      fileInput.value = "";
      await refresh();
    } catch (e) {
      status = e.message;
    } finally {
      busy = false;
    }
  }

  async function onDownload(id) {
    window.open(await downloadUrl(id), "_blank");
  }

  // Hard delete — confirm first (bytes are gone for good, no soft-delete here).
  async function onDelete(id, filename) {
    if (!confirm(`Delete "${filename}"? This can't be undone.`)) return;
    busy = true;
    try {
      await deleteUpload(id);
      status = "Deleted.";
      await refresh();
    } catch (e) {
      status = e.message;
    } finally {
      busy = false;
    }
  }
</script>

<main>
  <h1>File uploads <span class="tag">nestjs + svelte</span></h1>
  <p class="hint">
    PDF only, up to the server's size cap. The file goes straight to storage — it
    never passes through this server.
  </p>

  <section class="uploader">
    <input type="file" accept="application/pdf" bind:this={fileInput} />
    <button on:click={onUpload} disabled={busy}>Upload</button>
    <span class="status">{status}</span>
  </section>

  <h2>Uploads</h2>
  <ul class="list">
    {#if rows.length === 0}
      <li class="empty">No uploads yet.</li>
    {/if}
    {#each rows as r (r.id)}
      <li>
        <div>
          <div class="name">{r.filename}</div>
          <div class="meta">
            {fmtSize(r.size)} · {new Date(r.createdAt).toLocaleString()}
          </div>
        </div>
        <div class="row-actions">
          <span class="badge {r.status}">{r.status}</span>
          {#if r.status === "uploaded"}
            <button class="link" on:click={() => onDownload(r.id)}>Download</button>
          {/if}
          <button
            class="link danger"
            on:click={() => onDelete(r.id, r.filename)}
            disabled={busy}
          >Delete</button>
        </div>
      </li>
    {/each}
  </ul>
</main>
